version: 2.1
orbs:
  ship: auth0/ship@0.3.0
jobs:
  test:
    executor:
      name: ship/node
    steps:
      - checkout
      - ship/node-install-packages
      - run: npm run build
      - run: npm run lint
      - run: npm run test
      - store_test_results:
          path: test-results
workflows:
  build_test_publish:
    jobs:
      - test
      - ship/node-publish:
          publish-command: npm publish --workspace=packages/express-oauth2-jwt-bearer
          app-directory: "packages/express-oauth2-jwt-bearer"
          requires:
            - test
          context:
            - publish-npm
            - publish-gh
          filters:
            branches:
              only:
                - main
